name: bloc_clean
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  internet_connection_checker: ^1.0.0+1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.0
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1
  either_dart: ^0.3.0
  auto_route: ^6.0.5
  equatable: ^2.0.5
  get_it: ^7.2.0
  dartz: ^0.10.1
  formz: ^0.4.1
  intl: ^0.17.0
  dio: ^5.1.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^6.0.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3


flutter:
  assets:
    - assets/images/
    - assets/lang/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

  uses-material-design: true